name: svgaplayer_flutter
description: The SVGAPlayer implementation of Flutter using CustomPainter.
version: 2.2.0
homepage: https://github.com/yyued/SVGAPlayer-Flutter

environment:
  sdk: '>=2.19.3 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  protobuf:
  http: ^1.2.1
  path_drawing:
  archive:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
